"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, RefreshCw, RotateCcw, Scale, Settings2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectItem } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter } from "@/components/ui/dialog";
import { Can } from "@/lib/auth/can";
import { useUiControl } from "@/lib/auth/ui-control";
import { cn } from "@/lib/utils/cn";
import { formatAmount, formatDate, formatDateTime } from "@/lib/utils/format";
import { useCloseReconciliationPeriod, useConfirmReconciliation, useReconciliationCases, useReconciliationPeriods, useReconciliationSettings, useRejectReconciliation, useReverseReconciliation, useRunReconciliation, useUpdateReconciliationSettings } from "@/hooks/use-reconciliation";
import type { BankAccountListDto, ReconciliationCaseDto, ReconciliationDifferenceType, ReconciliationSettingsDto, ReconciliationStatus } from "@/types/api";

const differenceTypes: Array<{ value: ReconciliationDifferenceType; label: string }> = [
  { value: "None", label: "Sin diferencia" }, { value: "Commission", label: "Comisión bancaria" },
  { value: "Refund", label: "Devolución" }, { value: "Transfer", label: "Transferencia" },
  { value: "Timing", label: "Diferencia temporal" }, { value: "Other", label: "Otra justificación" },
];
const matchLabels = { Exact: "Exacta", Suggested: "Sugerida", OneToMany: "Uno a varios", ManyToOne: "Varios a uno", Partial: "Parcial", Difference: "Con diferencia" } as const;

function PermissionCheckbox({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) {
  const access = useUiControl({ controlKey: "ledger.reconciliation.settings.autoConfirm", permission: "ManageReconciliationSettings" });
  if (access.hidden) return null;
  return <label className="flex min-h-11 items-center justify-between gap-4 rounded-input border border-border bg-surface p-3" {...access.dataAttributes}><span><strong className="block text-sm text-foreground">Confirmar coincidencias exactas</strong><span className="text-xs text-muted">Sólo cuando alcanzan el umbral automático.</span></span><input data-ui-control="ui.components.modules.ledger.reconciliation.panel.input.1" type="checkbox" className="h-5 w-5 accent-action" checked={checked} disabled={access.disabled || access.readOnly} onChange={(event) => onChange(event.target.checked)} /></label>;
}

export function ReconciliationPanel({ accounts }: { accounts: BankAccountListDto[] }) {
  const today = new Date().toISOString().slice(0, 10);
  const monthStart = `${today.slice(0, 8)}01`;
  const [accountId, setAccountId] = useState(""); const [from, setFrom] = useState(monthStart); const [to, setTo] = useState(today);
  const [status, setStatus] = useState<ReconciliationStatus>("Suggested");
  const [reviewCase, setReviewCase] = useState<ReconciliationCaseDto | null>(null); const [reverseCase, setReverseCase] = useState<ReconciliationCaseDto | null>(null);
  const [differenceType, setDifferenceType] = useState<ReconciliationDifferenceType>("None"); const [reason, setReason] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false); const [periodOpen, setPeriodOpen] = useState(false);
  const selectedAccount = useMemo(() => accounts.find((item) => item.id === accountId), [accounts, accountId]);
  useEffect(() => { if (!accountId && accounts.length) setAccountId(accounts[0].id); }, [accounts, accountId]);
  const cases = useReconciliationCases(accountId || undefined, status); const periods = useReconciliationPeriods(accountId || undefined); const settings = useReconciliationSettings();
  const run = useRunReconciliation(); const confirm = useConfirmReconciliation(); const reject = useRejectReconciliation(); const reverse = useReverseReconciliation();

  const openReview = (item: ReconciliationCaseDto) => { setReviewCase(item); setDifferenceType(item.differenceType); setReason(item.differenceReason ?? ""); };
  const confirmCase = async () => { if (!reviewCase) return; await confirm.mutateAsync({ id: reviewCase.id, differenceType, differenceReason: reason || null }); setReviewCase(null); };
  const reverseConfirmed = async () => { if (!reverseCase || !reason.trim()) return; await reverse.mutateAsync({ id: reverseCase.id, reason: reason.trim() }); setReverseCase(null); setReason(""); };

  return <section aria-labelledby="reconciliation-title" className="space-y-5">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 id="reconciliation-title" className="font-display text-lg font-bold text-foreground">Motor de conciliación</h2><p className="mt-1 text-sm text-muted">Compará evidencia bancaria y contable antes de confirmar.</p></div><div className="flex flex-wrap gap-2"><Can permission="ManageReconciliationSettings"><Button controlKey="ledger.reconciliation.settings.open" permission="ManageReconciliationSettings" variant="outline" onClick={() => setSettingsOpen(true)}><Settings2 className="h-4 w-4" />Reglas</Button></Can><Can permission="CloseReconciliationPeriods"><Button controlKey="ledger.reconciliation.period.open" permission="CloseReconciliationPeriods" variant="secondary" onClick={() => setPeriodOpen(true)}><Scale className="h-4 w-4" />Cerrar periodo</Button></Can></div></div>
    <div className="grid gap-3 rounded-card border border-border bg-surface p-4 shadow-dp1 md:grid-cols-[1fr_160px_160px_auto] md:items-end">
      <Select controlKey="ledger.reconciliation.filters.account" permission="ViewReconciliation" label="Cuenta bancaria" value={accountId} onValueChange={setAccountId}>{accounts.map((account) => <SelectItem key={account.id} value={account.id}>{account.name} · {account.currency}</SelectItem>)}</Select>
      <Input controlKey="ledger.reconciliation.filters.from" permission="ViewReconciliation" type="date" label="Desde" value={from} onChange={(event) => setFrom(event.target.value)} />
      <Input controlKey="ledger.reconciliation.filters.to" permission="ViewReconciliation" type="date" label="Hasta" value={to} onChange={(event) => setTo(event.target.value)} />
      <Button controlKey="ledger.reconciliation.run" permission="RunReconciliation" loading={run.isPending} disabled={!accountId || !from || !to} onClick={() => run.mutate({ bankAccountId: accountId, from, to })}><Sparkles className="h-4 w-4" />Buscar coincidencias</Button>
    </div>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><Select controlKey="ledger.reconciliation.filters.status" permission="ViewReconciliation" label="Estado" value={status} onValueChange={(value) => setStatus(value as ReconciliationStatus)}><SelectItem value="Suggested">Pendientes</SelectItem><SelectItem value="Confirmed">Confirmadas</SelectItem><SelectItem value="Rejected">Descartadas</SelectItem><SelectItem value="Reversed">Revertidas</SelectItem></Select><p className="text-xs text-muted">{cases.data?.length ?? 0} casos en esta vista</p></div>
    {cases.isLoading ? <div className="rounded-card border border-border bg-surface p-8 text-sm text-muted">Analizando casos guardados…</div> : cases.isError ? <div role="alert" className="rounded-card bg-danger-soft p-5"><p className="font-semibold text-danger">No se pudieron cargar las conciliaciones.</p><Button controlKey="ledger.reconciliation.list.retry" permission="ViewReconciliation" variant="outline" className="mt-3" onClick={() => cases.refetch()}>Reintentar</Button></div> : !cases.data?.length ? <div className="rounded-card border border-dashed border-border-strong bg-surface p-10 text-center"><RefreshCw className="mx-auto h-9 w-9 text-muted" /><p className="mt-3 font-semibold text-foreground">No hay casos en este estado</p><p className="mt-1 text-sm text-muted">Ejecutá el motor para preparar coincidencias explicables.</p></div> : <div className="grid gap-4">{cases.data.map((item) => <CaseCard key={item.id} item={item} onReview={() => openReview(item)} onReject={() => reject.mutate({ id: item.id })} onReverse={() => { setReverseCase(item); setReason(""); }} />)}</div>}
    {!!periods.data?.length && <section aria-labelledby="closed-periods-title"><h3 id="closed-periods-title" className="font-display font-bold text-foreground">Periodos cerrados</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{periods.data.map((period) => <article key={period.id} className="rounded-input border border-border bg-surface p-3"><div className="flex items-center justify-between gap-2"><p className="font-semibold text-foreground">{formatDate(period.startDate)} — {formatDate(period.endDate)}</p><Badge variant={Math.abs(period.differenceAmount) < 0.01 ? "jade" : "saffron"}>{Math.abs(period.differenceAmount) < 0.01 ? "Cuadrado" : "Justificado"}</Badge></div><p className="mt-2 text-sm text-muted">Diferencia: {formatAmount(period.differenceAmount, period.currency)}</p>{period.justification && <p className="mt-1 text-xs text-foreground-secondary">{period.justification}</p>}</article>)}</div></section>}
    <Dialog open={!!reviewCase} onOpenChange={(open) => { if (!open) setReviewCase(null); }}><DialogContent title="Confirmar conciliación" description="La sugerencia no modifica saldos hasta tu confirmación." size="md">{reviewCase && <div className="space-y-4"><CaseComparison item={reviewCase} /><Select controlKey="ledger.reconciliation.confirm.differenceType" permission="ConfirmReconciliation" label="Tratamiento de diferencia" value={differenceType} onValueChange={(value) => setDifferenceType(value as ReconciliationDifferenceType)}>{differenceTypes.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</Select>{Math.abs(reviewCase.differenceAmount) > (settings.data?.amountTolerance ?? 0.01) && <Input controlKey="ledger.reconciliation.confirm.reason" permission="ConfirmReconciliation" label="Justificación *" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explicá la comisión, devolución o diferencia" />}</div>}<DialogFooter><Button controlKey="ledger.reconciliation.confirm.cancel" systemRequired variant="secondary" onClick={() => setReviewCase(null)}>Cancelar</Button><Button controlKey="ledger.reconciliation.confirm.submit" permission="ConfirmReconciliation" loading={confirm.isPending} disabled={!!reviewCase && Math.abs(reviewCase.differenceAmount) > (settings.data?.amountTolerance ?? 0.01) && (differenceType === "None" || !reason.trim())} onClick={confirmCase}><CheckCircle2 className="h-4 w-4" />Confirmar conciliación</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!reverseCase} onOpenChange={(open) => { if (!open) setReverseCase(null); }}><DialogContent title="Revertir conciliación" description="Se liberarán las partidas y quedará un evento auditable." size="sm"><Input controlKey="ledger.reconciliation.reverse.reason" permission="ReverseReconciliation" label="Motivo *" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Indicá por qué debe revertirse" /><DialogFooter><Button controlKey="ledger.reconciliation.reverse.cancel" systemRequired variant="secondary" onClick={() => setReverseCase(null)}>Cancelar</Button><Button controlKey="ledger.reconciliation.reverse.submit" permission="ReverseReconciliation" variant="danger" loading={reverse.isPending} disabled={!reason.trim()} onClick={reverseConfirmed}><RotateCcw className="h-4 w-4" />Revertir</Button></DialogFooter></DialogContent></Dialog>
    <SettingsDialog open={settingsOpen} onOpenChange={setSettingsOpen} value={settings.data} />
    <PeriodDialog open={periodOpen} onOpenChange={setPeriodOpen} accountId={accountId} from={from} to={to} currency={selectedAccount?.currency ?? "MXN"} />
  </section>;
}

function CaseCard({ item, onReview, onReject, onReverse }: { item: ReconciliationCaseDto; onReview: () => void; onReject: () => void; onReverse: () => void }) {
  return <article className="rounded-card border border-border bg-surface p-4 shadow-dp1"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant={item.score >= 90 ? "jade" : item.score >= 70 ? "primary" : "saffron"}>{item.score.toFixed(0)} puntos</Badge><Badge variant="muted">{matchLabels[item.matchType]}</Badge>{item.isAutomatic && <Badge variant="periwinkle">Automática exacta</Badge>}</div><p className="mt-2 text-xs text-muted">Generada {formatDateTime(item.generatedAt)}</p></div>{item.status === "Suggested" ? <div className="flex gap-2"><Button controlKey="ledger.reconciliation.case.reject" permission="ConfirmReconciliation" size="sm" variant="ghost" onClick={onReject}>Descartar</Button><Button controlKey="ledger.reconciliation.case.review" permission="ConfirmReconciliation" size="sm" onClick={onReview}>Revisar <ChevronRight className="h-4 w-4" /></Button></div> : item.status === "Confirmed" ? <Button controlKey="ledger.reconciliation.case.reverse" permission="ReverseReconciliation" size="sm" variant="danger" onClick={onReverse}><RotateCcw className="h-4 w-4" />Revertir</Button> : null}</div><CaseComparison item={item} /><div className="mt-4 flex flex-wrap gap-2">{item.factors.map((factor) => <span key={factor.code} className="rounded-full bg-action-soft px-3 py-1 text-xs text-action" title={factor.detail}>{factor.label} +{factor.points.toFixed(0)}</span>)}</div></article>;
}

function CaseComparison({ item }: { item: ReconciliationCaseDto }) { const currency = item.bankLines[0]?.currency ?? item.ledgerEntries[0]?.currency ?? "MXN"; return <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto_1fr]"><Party title="Banco" items={item.bankLines.map((line) => ({ id: line.id, date: line.date, description: line.description, reference: line.reference, amount: line.amount, applied: line.appliedAmount }))} currency={currency} /><div className="hidden items-center lg:flex"><ChevronRight className="h-5 w-5 text-muted" /></div><Party title="Contabilidad" items={item.ledgerEntries.map((entry) => ({ id: entry.id, date: entry.date, description: entry.description, reference: entry.reference, amount: entry.amount, applied: entry.appliedAmount }))} currency={currency} />{Math.abs(item.differenceAmount) > 0.001 && <div className="rounded-input bg-warning-soft p-3 text-sm text-warning lg:col-span-3"><strong>Diferencia:</strong> {formatAmount(item.differenceAmount, currency)}{item.differenceReason ? ` · ${item.differenceReason}` : " · requiere clasificación"}</div>}</div>; }
function Party({ title, items, currency }: { title: string; items: Array<{ id: string; date: string; description: string; reference?: string | null; amount: number; applied: number }>; currency: string }) { return <div className="rounded-input bg-surface-subtle p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">{title} · {items.length}</p><div className="mt-2 space-y-2">{items.map((item) => <div key={item.id} className="border-t border-border pt-2 first:border-0 first:pt-0"><div className="flex justify-between gap-3"><p className="min-w-0 truncate text-sm font-semibold text-foreground">{item.description}</p><p className="shrink-0 text-sm font-bold text-foreground">{formatAmount(item.applied, currency)}</p></div><p className="mt-1 text-xs text-muted">{formatDate(item.date)}{item.reference ? ` · ${item.reference}` : ""} · original {formatAmount(item.amount, currency)}</p></div>)}</div></div>; }

function SettingsDialog({ open, onOpenChange, value }: { open: boolean; onOpenChange: (open: boolean) => void; value?: ReconciliationSettingsDto }) {
  const update = useUpdateReconciliationSettings(); const [form, setForm] = useState<ReconciliationSettingsDto | null>(null);
  useEffect(() => { if (open && value) setForm(value); }, [open, value]); if (!form) return null;
  const number = (key: keyof ReconciliationSettingsDto, next: string) => setForm((current) => current ? { ...current, [key]: Number(next) } : current);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title="Reglas del motor" description="Los pesos deben sumar 100 y cada sugerencia mostrará su explicación." size="lg"><div className="grid gap-3 sm:grid-cols-2"><Input controlKey="ledger.reconciliation.settings.dateTolerance" permission="ManageReconciliationSettings" type="number" min="0" max="30" label="Tolerancia de fecha (días)" value={form.dateToleranceDays} onChange={(event) => number("dateToleranceDays", event.target.value)} /><Input controlKey="ledger.reconciliation.settings.amountTolerance" permission="ManageReconciliationSettings" type="number" min="0" step="0.01" label="Tolerancia de importe" value={form.amountTolerance} onChange={(event) => number("amountTolerance", event.target.value)} /><Input controlKey="ledger.reconciliation.settings.suggestionThreshold" permission="ManageReconciliationSettings" type="number" min="0" max="100" label="Umbral de sugerencia" value={form.suggestionThreshold} onChange={(event) => number("suggestionThreshold", event.target.value)} /><Input controlKey="ledger.reconciliation.settings.autoThreshold" permission="ManageReconciliationSettings" type="number" min="0" max="100" label="Umbral automático exacto" value={form.autoConfirmThreshold} onChange={(event) => number("autoConfirmThreshold", event.target.value)} /></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{(["amountWeight", "dateWeight", "referenceWeight", "clientWeight", "patternWeight"] as const).map((key) => <Input key={key} controlKey={`ledger.reconciliation.settings.${key}`} permission="ManageReconciliationSettings" type="number" min="0" max="100" label={{amountWeight:"Importe",dateWeight:"Fecha",referenceWeight:"Referencia",clientWeight:"Cliente",patternWeight:"Patrón"}[key]} value={form[key]} onChange={(event) => number(key, event.target.value)} />)}</div><div className="mt-4"><PermissionCheckbox checked={form.allowAutoConfirmExact} onChange={(allowAutoConfirmExact) => setForm({ ...form, allowAutoConfirmExact })} /></div><p className={cn("mt-3 text-xs", form.amountWeight + form.dateWeight + form.referenceWeight + form.clientWeight + form.patternWeight === 100 ? "text-success" : "text-danger")}>Suma de pesos: {form.amountWeight + form.dateWeight + form.referenceWeight + form.clientWeight + form.patternWeight}/100</p><DialogFooter><Button controlKey="ledger.reconciliation.settings.cancel" systemRequired variant="secondary" onClick={() => onOpenChange(false)}>Cancelar</Button><Button controlKey="ledger.reconciliation.settings.save" permission="ManageReconciliationSettings" loading={update.isPending} disabled={form.amountWeight + form.dateWeight + form.referenceWeight + form.clientWeight + form.patternWeight !== 100} onClick={async () => { await update.mutateAsync(form); onOpenChange(false); }}>Guardar reglas</Button></DialogFooter></DialogContent></Dialog>;
}

function PeriodDialog({ open, onOpenChange, accountId, from, to, currency }: { open: boolean; onOpenChange: (open: boolean) => void; accountId: string; from: string; to: string; currency: string }) { const close = useCloseReconciliationPeriod(); const [type, setType] = useState<ReconciliationDifferenceType>("None"); const [justification, setJustification] = useState(""); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title="Cerrar periodo conciliado" description="El cierre exige que todas las partidas estén conciliadas; cualquier diferencia debe justificarse." size="md"><div className="grid gap-3 sm:grid-cols-2"><Input controlKey="ledger.reconciliation.period.from" permission="CloseReconciliationPeriods" type="date" label="Desde" value={from} readOnly /><Input controlKey="ledger.reconciliation.period.to" permission="CloseReconciliationPeriods" type="date" label="Hasta" value={to} readOnly /></div><p className="mt-3 rounded-input bg-surface-subtle p-3 text-sm text-muted">Cuenta en {currency}. El servidor recalculará ambos totales antes de cerrar.</p><div className="mt-3"><Select controlKey="ledger.reconciliation.period.differenceType" permission="CloseReconciliationPeriods" label="Clasificación si existe diferencia" value={type} onValueChange={(value) => setType(value as ReconciliationDifferenceType)}>{differenceTypes.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</Select></div><div className="mt-3"><Input controlKey="ledger.reconciliation.period.justification" permission="CloseReconciliationPeriods" label="Justificación" value={justification} onChange={(event) => setJustification(event.target.value)} /></div><DialogFooter><Button controlKey="ledger.reconciliation.period.cancel" systemRequired variant="secondary" onClick={() => onOpenChange(false)}>Cancelar</Button><Button controlKey="ledger.reconciliation.period.close" permission="CloseReconciliationPeriods" loading={close.isPending} disabled={!accountId} onClick={async () => { await close.mutateAsync({ bankAccountId: accountId, startDate: from, endDate: to, differenceType: type, justification: justification || null }); onOpenChange(false); }}>Cerrar periodo</Button></DialogFooter></DialogContent></Dialog>; }
